### ISSUE TITLE
Consolidate all the .sh files into a single one

### ISSUE THREAD

**Issue by erikbor** [riboseinc/aws-authenticating-secgroup-scripts#11]
Hi @phuonghuynh,

Could you please consolidate all the .sh files into a single one? We are integrating your script in our workflow for authenticating against the Lambda endpoint for dynamic secgroups and IAM groups.
Your scripts now directly source `__invoke_it__.sh` assuming it's in the `cwd`:

```sh
#!/bin/bash

. __invoke_it__.sh

invoke_it "POST"
```
This requires us to `cd` into that directory first. It would be much easier for integration if we can call a single script using an absolute path.

Thanks

**Comment by phuonghuynh** [comment]
Yes
